data_dir = "/tmp/vector"

[sources.tcp_in]
  type = "tcp"
  address = "127.0.0.1:8080"

[sinks.http_out]
  type = "http"
  inputs = ["tcp_in"]
  uri = "http://localhost:8082"
  encoding = "json"

[sinks.http_out.buffer]
  type = "disk"
  max_size = 104900
  when_full = "block"